language: ruby

sudo: false

cache: bundler

before_install:
  - gem update --system
  - gem install bundler -v 1.16.1
bundler_args: --without development
rvm:
  - 2.6.0
  - 2.4.2

script:
  - bundle exec rake lint
  - bundle exec rake spec
