language: ruby

sudo: false

cache: bundler

before_install:
  - gem update --system
  - gem install bundler
bundler_args: --without development
rvm:
  - 2.4.2
  - ruby-head
  
script:
  - bundle exec rake lint
  - bundle exec rake spec
